### PR TITLE
minify and shrinkResources in release builds

### PR DESCRIPTION
**Pull request by Aeyoun**

### CODE REVIEW

**Comment by bkerensa** [comment]
This fails red

**Comment by PaoloRotolo** [comment]
Minify isn't supported by some libraries we use. That's why it fails.

**Comment by bkerensa** [comment]
Can we check with those libraries to see if they can add support? Does minify benefit us?

**Comment by PaoloRotolo** [comment]
Realm has some problems with it. I'll try to search if there's a workaround.

**Comment by Aeyoun** [comment]
I did actually write a long description when submitting this issue. Must have gotten lost in the void. The crux of it was that I tried getting this to work unsuccessfully but wanted to open a pull request as it was worth investigating. Hoped you guys who knew the code better would have better ideas on how to achieve this. Minify just gets the app to a place where zip alignment makes sense and would boost start-up performance and lower memory usage.

**Comment by bkerensa** [comment]
Excellent we will look into this @PaoloRotolo can we file a bug upstream and see if they might make a fix?

**Comment by PaoloRotolo** [comment]
Fixed in 0.9.2. You had to specify a custom ProGuard config file to find Realm proxy class after obfuscation.

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**
```

**Pull request closed without merging**
