### PR TITLE
Reduce ReadingTools.java hourToSpinnerType code to understand easily

### PR DESCRIPTION
**Pull request by HyungJiny**
I think that the case if hour is over 23 is don't need if you using '%' operation.
And 'return 8' repeated.
I think my code can reduce repeat code.

### CODE REVIEW

**Comment by bkerensa** [comment]
@paolorotolo

**Comment by emartynov** [comment]
Hey! You're right that that case will never run `23 % 23 == 0` and we will never have 24 as hour value. However, I think it might be a bug also, since I expect app should predict sometimes night mode. The question is "when".

**Comment by bkerensa** [comment]
@paolorotolo any thoughts on this?

**Comment by emartynov** [comment]
I'm really sorry, but I'm closing PR (due to lack of review and attention to answer to this problem)

**Pull request closed without merging**
