### PR TITLE
Add buttons to get the app

### PR DESCRIPTION
**Pull request by Poussinou**
Buttons with links to F-Droid and Google Play Store

### CODE REVIEW

**Comment by emartynov** [comment]
I would probably put Google play link first. And LGTM

**Comment by Poussinou** [comment]
Done

**Comment by emartynov** [comment]
@bkerensa no legal issues?

**Comment by bkerensa** [comment]
I'm not clear why we would add appstore buttons in the app? If they already have the app why would they need to download it again.

**Comment by emartynov** [comment]
This is an addition to our README file. You can view the [result](https://github.com/Poussinou/glucosio-android/blob/364dd87f72a02f84eeaecb970e10df475dd89ddf/README.md).

**Comment by Poussinou** [comment]
Sometimes I find interesting repos but I do not have the app itself. This buttons can be useful for this kind of people, and it can be useful to have a link where you can find the app build and signed... But I can close the PR if needed

**Comment by paolorotolo** [comment]
Looks good to me.

**Pull request merged**
