### PR TITLE
Modifications for landscape orientation

### PR DESCRIPTION
**Pull request by weslly99**
add files to landscape orientation

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
Hi,
can you please sign our Individual Contributor License Agreement first?
https://www.clahub.com/agreements/Glucosio/glucosio-android
Thanks!

**Comment by weslly99** [comment]
Hi, Paolo I'm agree  :)

**Comment by PaoloRotolo** [comment]
Ok, do we really need another layout file for landscape activities?
Maybe the same layout works good both in portrait and landscape without changes.

**Comment by weslly99** [comment]
yes. some devices some fields hidden in landscape orientation

<b>Before: Galaxy Win Duos, Android Jelly Bean</b>
before

<b>Before: Moto G, Android Lollipop</b>
motog


<b>After:</b>
after

**Comment by bkerensa** [comment]
@PaoloRotolo Can you review this once more and do some testing and if its good accept it?

**Comment by bkerensa** [comment]
Update on this?

**Comment by PaoloRotolo** [comment]
@weslly99 Nice, it looks good. Can you please update your pull with latest changes? I've some code conflicts right now.

**Comment by satya164** [comment]
Seems unnecessary to duplicate everything when we're basically only changing the padding. Can't we put the common code in a single xml file and then reuse it?

**Comment by weslly99** [comment]
@satya164 All right, using fragment can do... this will change many things.
@PaoloRotolo you know otherwise of do this?

**Comment by PaoloRotolo** [comment]
Can we check programmatically if orientation is landscape and if yes adjust padding and don't size?

**Comment by PaoloRotolo** [comment]
font* sorry,

**Comment by weslly99** [comment]
For this situation, maintain XML.

pros: 
1. Keeps a separation between the visual design, and the functionality. 
2. Ease future change.

cons: 
1. More files
2. Don't repeat yourself (DRY)

Programmatically

pros:
1. don't duplicate XML  

cons:
1. functionality and visual design in same place.
2. hight  coupling 

without using fragment, I prefer use a XML for landscape orientation. 
(I'm not saying that this, is the best solution)

**Comment by bkerensa** [comment]
Is this still pending or are we closing this?

**Comment by satya164** [comment]
Any updates on this @weslly99 @PaoloRotolo ?

**Comment by weslly99** [comment]
Sorry for the absence @satya164 @bkerensa  @PaoloRotolo. This new design is very useful. Solved the problem when land orientation.

**Comment by PaoloRotolo** [comment]
Cool, I'm closing this.

**Pull request closed without merging**
