### PR TITLE
Add bottom sheet menu

### PR DESCRIPTION
**Pull request by PaoloRotolo**

### CODE REVIEW

**Comment by emartynov** [comment]
686 files changed?

**Comment by PaoloRotolo** [comment]
I noticed Codacy complaining about some unused imports so I ran Android Studio's utility to clean and rearrange code to improve readability and that happened. You should only look to previous commits.

**Comment by emartynov** [comment]
@PaoloRotolo I didn't test it. But from looking code it is fine

**Comment by PaoloRotolo** [comment]
We've time, I'm waiting you to test it so we don't introduce issues :+1:

**Comment by emartynov** [comment]
Two comments:
 1. Fade out happens only fo part of activity. Also, it doesn't prevent me to press on the different elements of the activity - dropbox, tabs, drawer. All they are enabled.
 2. It has conflicts.

**Comment by PaoloRotolo** [comment]
@emartynov fixed issue 1. I think I'll resolve manually the conflicts (they're probably generated by Android's code optimizer).

**Comment by PaoloRotolo** [comment]
Okay, I'll merge it now. Thanks.

**Pull request closed without merging**
