### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by emartynov**
Changes:

1. I stole a nice way to keep dependencies clean from Jake's project https://github.com/JakeWharton/SdkSearch/blob/master/build.gradle.
2. Modified all build scripts to work with it correctly.
3. I've also cleaned up unused repositories, dependencies that are included by default.
4. Updated almost all dependencies to the latest.
5. Added one finally block to close resource if an error happens in BackupActivity and small cleanup in this file.
6. Also use latest gradle in wrapper now.

Please review and comment.

### CODE REVIEW

**Comment by emartynov** [comment]
I'm checking coverage issue now.

**Review by ghost — COMMENTED** [review]
Looks good to me. Just wondering about extracting `applicationId 'org.glucosio.android'` - as an example to `buildConfig.applicationId` to keep it all in one place.

**Comment by AndyScherzinger** [comment]
I guess the application id isn't extracted since it is "fixed"

**Comment by paolorotolo** [comment]
Looks good to me, awesome!

**Pull request merged**
