### PR TITLE
Fix issue #369

### PR DESCRIPTION
**Pull request by paolorotolo**
Fix issue #369 using AlarmManager.setExact()

### CODE REVIEW

**Comment by emartynov** [comment]
LGTM! Lets wait for Travis

**Comment by paolorotolo** [comment]
Travis error, I'm restarting the build.

**Comment by paolorotolo** [comment]
Uh: https://www.traviscistatus.com/incidents/c1s4dlyxd4lf

**Comment by paolorotolo** [comment]
Travis is back online and CI passed. Merging this.

**Pull request merged**
