### PR TITLE
Update OverviewFragment.java

### PR DESCRIPTION
**Pull request by joaosardinha**
getResources().getColor() is deprecated, ContextCompat.getColor() on the other hand... :)

### CODE REVIEW

**Comment by raacker** [comment]
Could you rebase your commits?

**Comment by emartynov** [comment]
Thank you for the contribution! Could you also change other places in the application that use the deprecated API? Quick search shows me `HistoryAdpater`, `HistoryFragment`, `DataLayerListenerServices`, `GlucoseRanges`, `GlucosioNotificationManager`, `LabeledSpinner`.

**Comment by bkerensa** [comment]
@joaosardinha ping

**Comment by emartynov** [comment]
I'm closing PR because of no activity. Please reopen if you want to continue on it.

**Pull request closed without merging**
