### PR TITLE
Update dependencies.gradle

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Nice. You forgot to update `.travis.yml` file which has older build tools version, exactly:
```    - build-tools-27.0.2 ``` whereas yours dependencies.gradle has `27.0.3`. That's why Travis builds are failing and I think this should be fixed in this pull request.

**Comment by emartynov** [comment]
@piotrek1543 did you quickly checked that no issues are introduced with deps update?

**Comment by emartynov** [comment]
Tested build by quick run and it works!

**Comment by ghost** [comment]
@emartynov sorry for being late. No, I didn't check it.

**Pull request merged**
