### PR TITLE
Adding PowerMock library

### PR DESCRIPTION
**Pull request by raacker**
I was writing test case of some classes, mockito can't test static methods.
So I'm trying to add PowerMock library.

I'm making PR to ask. Would adding it great? or any other suggestion?

### CODE REVIEW

**Comment by emartynov** [comment]
Can you give example what are you trying to test that requires PowerMock?

**Comment by raacker** [comment]
Ah it is depend on if GlucosioConverter changed to utility class.

**Comment by emartynov** [comment]
Just merged

**Comment by raacker** [comment]
Okay then GlucosioConverter has static method and mockito can't test static methods.

http://stackoverflow.com/questions/21105403/mocking-static-methods-with-mockito

and that's what I'm gonna trying to code :)

**Comment by emartynov** [comment]
Mockito is not testing anything!

You don't need to mock static methods just use the same method in the test.

**Comment by raacker** [comment]
Oh ... hmm then can you suggest how to test this method? I don't know what I can do with this :)

[saveA1C method](https://github.com/Glucosio/glucosio-android/blob/develop/app/src/main/java/org/glucosio/android/presenter/A1CCalculatorPresenter.java#L73)

**Comment by raacker** [comment]
oh... okay! got this :) I think powermock doens't need. Need to close this PR :)

**Comment by emartynov** [comment]
I think so! Please close it!

**Pull request closed without merging**
