### PR TITLE
Save pager state when editing a reading (Closes #270).

### LINKED ISSUE #270: Navigation back from edit leaves you on graph
Steps:
 1. Go to history
 2. Select one of the readings and choose edit
 3. Finish editing or press back

Expected: to come back to the same screen where I was before.
Actual: I'm back to the graph.

### PR DESCRIPTION
**Pull request by PaoloRotolo**

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
Please review and merge.

**Comment by bkerensa** [comment]
@emartynov Have you had a chance to look at this?

**Comment by emartynov** [comment]
This doesn't restore position for the dropdown. Yes you come back to history fragment but you see glucose readings even if you started editing something else.

**Comment by PaoloRotolo** [comment]
Done, can you check please?

**Comment by emartynov** [comment]
Works! Merging now

**Comment by HarKoss** [comment]
Cool :D

**Pull request merged**
