### PR TITLE
Issue #330 - Added the espresso test for invalid age error toast

### PR DESCRIPTION
**Pull request by ArunSelvam11**
Please review & merge the branch to develop.
Got this issue from codetriage.com.
Thank you.

### CODE REVIEW

**Comment by emartynov** [comment]
Hey, thanks for the contribution. I'm checking it now!

**Comment by paolorotolo** [comment]
I'll leave to @emartynov the final word on it, he's our tests guy :D

**Review by ghost — COMMENTED** [review]
This merge request covers only one of possible cases:

``` 
   private boolean validateAge(String age) {
        if (TextUtils.isEmpty(age)) {
            return false;
        } else if (!TextUtils.isDigitsOnly(age)) {
            return false;
        } else {
            int finalAge = Integer.parseInt(age);
            return finalAge > 0 && finalAge < 120; //THIS ONE
        }
    }
```
The first case - no value - would be another case like `check_011__IfIEnterNoValueForAge`, so it does not matter for now. The second one and the last depend on what we mean by `wrongAge`.

For me, this test case is enough to merge, because it checks if there is any effect of wrong input - it should display `Toast` with message. This test checks it ;-)

**Comment by emartynov** [comment]
Thank you for the contribution! Merging!

**Pull request merged**
