### PR TITLE
Solving the CSV Export problem on Samsung S6

### PR DESCRIPTION
**Pull request by Ghazghkull**
The main problem seems to be related witth the static method exporting the CSV.

Creating the needed class every time into the new thread solves the problem

### CODE REVIEW

**Comment by satya164** [comment]
Why does the error happen with a static method?

**Comment by Ghazghkull** [comment]
@satya164 , I think you can find the response here: [](http://stackoverflow.com/questions/17343157/static-method-behavior-in-multi-threaded-environment-in-java)

**Comment by paolorotolo** [comment]
So I talked with @bkerensa. Even if we fully don't understand why the error occurs, a fix is better than nothing. @Ghazghkull I see a conflict (sorry :P), can you please solve it? I will merge after.

**Comment by Ghazghkull** [comment]
This night when I can access to my personal computer, I will solve the conflict :)

**Comment by paolorotolo** [comment]
I solved some problems with dependencies. Now you should be able to compile without issues :)

**Comment by Ghazghkull** [comment]
Thanks, last night I had a lot of errors and I din't know why....

**Comment by paolorotolo** [comment]
Merged, thanks!

**Pull request merged**
