### PR TITLE
Fixing #121 and #129 issues, changing Overview layout, adding Espresso UI tests

### PR DESCRIPTION
**Pull request by piotrek1543**

### CODE REVIEW

**Comment by PaoloRotolo** [comment]
Hi @piotrek1543,
thanks for your pull request.

May I ask why did you downgrade Android support libraries from 23.1.0 to 23.0.1?

**Comment by amouly** [comment]
@PaoloRotolo apparently the Espresso library depends on the Annotations library version 23.0.1, so it's not working with our current configuration. But we can avoid this issue just forcing the Testing runner to use the newer version. On my fork I have the working sample of this.

**Comment by PaoloRotolo** [comment]
@amouly thanks for the tip. @piotrek1543 Can you fix that in your fork?

**Comment by piotrek1543** [comment]
@amouly @PaoloRotolo  I changed android support dependencies to 23.1.0 and added new Realm version. It works ;-)

**Comment by PaoloRotolo** [comment]
LGTM, thanks!

**Pull request merged**
