### PR TITLE
Restore existing espresso tests. 

### PR DESCRIPTION
**Pull request by rcd27**
There are some espresso tests which do not work properly right now. This PR is about restoring them to pass again.

### CODE REVIEW

**Comment by rcd27** [comment]
Well, HelloActivityTest was restored, however I think layout is broken. This is supposed to pass without scrolling to CheckBox. When I open activity_hello.xml check box is visible on the same screen without any scrolling.

**Comment by emartynov** [comment]
Could you pull upstream and rebase your branch on top of it?

**Comment by rcd27** [comment]
Really do not know what to do with that "Demeter" violation...

**Comment by emartynov** [comment]
Thank you for the contribution

**Pull request merged**
